theme = Gruvbox Dark Hard
font-size = 10
gtk-titlebar=false
background-opacity = .95
mouse-hide-while-typing = true
window-decoration = none
font-family = "0xProto Nerd Font Mono"
app-notifications = no-clipboard-copy
