#!/bin/bash

output=$(sp metadata)
artist=$(echo "$output" | grep "artist|" | cut -c 8-)
image=$(echo "$output" | grep "artUrl|" | cut -c 7-)
album=$(echo "$output" | grep "album|" | cut -c 7-)
track=$(echo "$output" | grep "title|" | cut -c 7-)

# if artist is empty but album is not then it is a poddast
if [ -z "$artist" ] && [ ! -z "$album" ]; then
    artist="$album"
fi

if [ -z "$artist" ]; then
    notify-send "No track is currently playing."
    exit 1
fi

notify-send -i notification-audio-play "$track" "$artist"

