#!/bin/sh

SIDEBAR=false

if [ "$1" = "--sidebar" ]; then
    SIDEBAR=true
    shift
fi

if [ $# -ne 2 ]; then
    echo "Usage: ${0} [--sidebar] <i3_mark> <launch_cmd>"
    echo "Example: ${0} 'scratch-emacs' 'emacsclient -c -a emacs'"
    echo "Example: ${0} --sidebar 'scratch-emacs' 'emacsclient -c -a emacs'"
    exit 1
fi

I3_MARK=${1}
LAUNCH_CMD=${2}

# calculate the width and height of the screen
# SCREEN_WIDTH=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1)
# print $SCREEN_WIDTH

scratchpad_show() {
    # screen width of monitor that is currently focsed with only one return value minus 200
    # make string into integer
    SCREEN_WIDTH=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1 | head -n 1)

    # screen height of monitor that is currently focsed with only one return value minus 200
    # make string into integer
    SCREEN_HEIGHT=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2 | head -n 1)

    if [ "${SIDEBAR}" = true ]; then
        SIDEBAR_Y=24
        SIDEBAR_WIDTH=$((SCREEN_WIDTH * 11 / 30))
        SIDEBAR_X=$((SCREEN_WIDTH - SIDEBAR_WIDTH))
        SIDEBAR_HEIGHT=$((SCREEN_HEIGHT - SIDEBAR_Y))

        i3-msg "[con_mark=${I3_MARK}]" scratchpad show, resize set $SIDEBAR_WIDTH $SIDEBAR_HEIGHT, move position $SIDEBAR_X $SIDEBAR_Y
    else
        SCREEN_WIDTH=$((SCREEN_WIDTH - 200))
        SCREEN_HEIGHT=$((SCREEN_HEIGHT - 100))

        i3-msg "[con_mark=${I3_MARK}]" scratchpad show, resize set $SCREEN_WIDTH $SCREEN_HEIGHT, move position center
    fi
}

# try showing the scratchpad window
if ! scratchpad_show; then
    # if there is no such window...

    # launch the application.
    eval "${LAUNCH_CMD}" &

    # Wait for the next window event.
    i3-msg -t subscribe  '[ "window" ]'

    # Set a mark
    i3-msg mark ${I3_MARK}

    # Move it to the scratchpad workspace
    i3-msg move scratchpad

    # show the scratchpad window
    scratchpad_show
fi
