#!/usr/bin/bash

if [ -f package.json ]; then
    DIR_STEM=$(jq -r '.name' package.json)
else
    DIR_STEM=$(basename "$PWD")
fi

# replace spaces with hyphens and punctiation with hyphens
DIR_STEM=$(echo $DIR_STEM | sed -E 's/[^a-zA-Z0-9]+/-/g')

# Check if a tmux session with the same name already exists
if tmux has-session -t $DIR_STEM 2>/dev/null; then
    echo "A tmux session named '$DIR_STEM' already exists. Attaching to it."
    tmux attach-session -t $DIR_STEM
    exit 0
fi

tmux new-session -d -s $DIR_STEM
tmux rename-window -t $DIR_STEM:1 'code'
tmux new-window -t $DIR_STEM:2 -n 'dev'
tmux new-window -t $DIR_STEM:3 -n 'git'

tmux send-keys -t $DIR_STEM:3 'lazygit' C-m
tmux send-keys -t $DIR_STEM:1 'v' C-m
tmux attach -t $DIR_STEM
tmux select-window -t $DIR_STEM:1

# go to window 1

