#!/bin/zsh

# Directory containing the notes
NOTES_DIR=~/Insync/rheajt@gmail.com/drive/Obsidian/

openInTerminal() {
    local filename="$1"
    notify-send "$filename"
    # Open the file in a terminal using nvim
    # alacritty -e bash -c "cd '$dir' && nvim '$note'"
    # Ensure the file exists or create it
    # Open the file in a terminal using nvim
    ghostty -e zsh -lc "cd $NOTES_DIR && nvim '$filename'"
}

newNote() {
    openInTerminal "$NOTES_DIR/temp.md"
}

listNotes() {
    FILES=$(fd . $NOTES_DIR --extension md --type f --hidden --exclude .git --exclude node_modules)
    # FILES=$(ls -t1 ~/notes/**/*.norg)
    # Check if files are found
    if [ -z "$FILES" ]; then
        echo "No markdown files found in $NOTES_DIR"
        exit 1
    fi

    SELECTED=$(echo "New\n$FILES" | rofi -dmenu -sorting-method fzf -sort -matching fuzzy -p "Notes")

    # Check if rofi returned a selection
    if [ -z "$SELECTED" ]; then
        echo "No selection made."
        exit 0
    fi

    # echo $SELECTED

    case "$SELECTED" in
        New) newNote ;;
        *) openInTerminal $SELECTED ;;
    esac
}

listNotes

