#!/usr/bin/env bash

local MAIN_DIR=~/projects
local PROJECT_TYPE=$(ls $MAIN_DIR | fzf)
local PROJECT=$(ls $MAIN_DIR/$PROJECT_TYPE | fzf)
local FULL_PATH=$MAIN_DIR/$PROJECT_TYPE/$PROJECT

cd $FULL_PATH
