#!/usr/bin/env bash

selected=$(echo "Single,Mirror,Multi" | rofi -dmenu -sep ',' -p "Select screen setup:")


# echo $selected
case "$selected" in
    "Single") xrandr --output HDMI-1 --off
    ;;

    "Mirror") 
        xrandr --output HDMI-1 --same-as eDP-1
    ;;

    "Multi") xrandr --output eDP-1 --auto --below HDMI-1 
    ;;

    *) echo default
    ;;
esac
