#!/usr/bin/env bash

# if there are no sessions, echo message and exit
if [ -z "$(tmux ls 2>/dev/null)" ]; then
    echo "No tmux sessions found."
    exit 0
fi
test=$(tmux ls 2>/dev/null | fzf --reverse --height=40% --preview 'tmux list-windows -t {1} -F "#{window_index}: #{window_name} (#{window_panes} panes)"' | awk '{print $1}')

if [ -z "$test" ]; then
    exit 0
fi
stripped=$(echo $test | sed 's/://g')

# determine if already in a tmux session
if [ -n "$TMUX" ]; then
    tmux switch-client -t $test
    exit 0
fi

tmux attach-session -t $stripped
