#!/usr/bin/env bash

test=$(tmux ls | fzf --reverse --height=~40% | awk '{print $1}')

if [ -z "$test" ]; then
    exit 0
fi
stripped=$(echo $test | sed 's/://g')

# determine if already in a tmux session
if [ -n "$TMUX" ]; then
	tmux switch-client -t $test
	exit 0
fi

tmux attach-session -t $stripped
