#!/usr/bin/env bash

PROFILE=$(printf "Full Charge\nBalanced\nMax Lifespan" | fzf --reverse --preview='')

case "$PROFILE" in
    "Full Charge") sudo system76-power charge-thresholds --profile full_charge ;;
    "Balanced") sudo system76-power charge-thresholds --profile balanced ;;
    "Max Lifespan") sudo system76-power charge-thresholds --profile max_lifespan ;;
    *) ;;
esac
