#!/bin/zsh
#
# .zshenv - Zsh environment file, loaded always.
#

# NOTE: .zshenv needs to live at ~/.zshenv, not in $ZDOTDIR!

# Set ZDOTDIR if you want to re-home Zsh.
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
export XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
export XDG_BIN_DIR=${XDG_BIN_DIR:-$HOME/.local/bin}
export ZDOTDIR=${ZDOTDIR:-$XDG_CONFIG_HOME/zsh}

# Ensure path arrays do not contain duplicates.
typeset -gU path fpath

# Set the list of directories that zsh searches for commands.
path=(
  $HOME/{,s}bin(N)
  $HOME/.local/{,s}bin(N)
  /opt/{homebrew,local}/{,s}bin(N)
  /usr/local/{,s}bin(N)
  $path
)

. "$HOME/.cargo/env"

export PATH=$HOME/projects/dotfiles/bash-scripts:$HOME/.local/sh:/usr/local/bin:$PATH

if [[ -d "$HOME/bin" ]]; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [[ -d "$HOME/.local/bin" ]] && [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
    export PATH="$HOME/.local/bin:$PATH"
fi

# User configuration
export ZVM_VI_INSERT_ESCAPE_BINDKEY=jk
export EDITOR="nvim"
export ZVM_VI_EDITOR="nvim"
export HISTSIZE=10000
export SAVEHIST=10000
export HISTFILE=~/.local/zsh_history
export MANPATH="/usr/local/man:$MANPATH"
export LANG=en_US.UTF-8
export GTK_USE_PORTAL=1
export SNACKS_GHOSTTY=true

export XDG_CURRENT_DESKTOP=Gnome
export XDG_DESKTOP_PORTAL_DIR=Gnome

# set up the chatgpt secret
export OPENAI_API_KEY=$(gpg -d ~/.config/chatgpt/chatgpt-secret.txt.gpg 2>/dev/null)
export OPENAI_KEY=$(gpg -d ~/.config/chatgpt/chatgpt-secret.txt.gpg 2>/dev/null)

# fzf
export FZF_DEFAULT_COMMAND='fd --type f --color=never --hidden'
export FZF_DEFAULT_OPTS="--height 60% --reverse --border --color=bg+:#343d46,gutter:-1,pointer:#ff3c3c,info:#4b84db,hl:#4b84db,hl+:#4b84db --preview 'batcat --color=always --style=numbers {}'"

export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_CTRL_T_OPTS="--preview 'batcat --color=always --line-range :50 {}'"

export FZF_CTRL_R_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_CTRL_R_OPTS="--height 60% --reverse --border --preview ''"

export FZF_ALT_C_COMMAND='fd --type d . --color=never --hidden'
export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -50'"

# fnm
export PATH="/home/jordanrhea/.local/share/fnm:$PATH"
eval "`fnm env --use-on-cd`"

# bun completions
[ -s "/home/jordanrhea/.bun/_bun" ] && source "/home/jordanrhea/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"


# pnpm
export PNPM_HOME="/home/jordanrhea/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# opencode
export PATH=/home/jordanrhea/.opencode/bin:$PATH

echo "Zsh environment loaded from ~/.zshenv"
